/*
 * Hardcoded Tennessee Eastman Process P&ID topology on a 1200x800 canvas.
 *
 *                            purge gas / analyzer
 *                                  |
 *                                  v
 * feeds -> [Reactor] -> [Condenser] -> [Separator] -> [Stripper] -> product
 *    ^        |                         |     ^
 *    |        |                         v     |
 *    +--------+------- [Compressor] <--- recycle/overhead
 *
 * if layout is wrong, lines will cross chaotically or units will overlap.
 */

export const TEP_LAYOUT = {
  canvas: {
    width: 1200,
    height: 800,
  },
  units: {
    reactor: {
      id: "reactor",
      label: "Reactor",
      type: "reactor",
      x: 220,
      y: 300,
      width: 120,
      height: 170,
    },
    condenser: {
      id: "condenser",
      label: "Condenser",
      type: "heat-exchanger",
      x: 430,
      y: 235,
      width: 120,
      height: 74,
    },
    separator: {
      id: "separator",
      label: "Separator",
      type: "separator",
      x: 620,
      y: 300,
      width: 170,
      height: 90,
    },
    stripper: {
      id: "stripper",
      label: "Stripper",
      type: "stripper",
      x: 940,
      y: 285,
      width: 110,
      height: 190,
    },
    compressor: {
      id: "compressor",
      label: "Compressor",
      type: "compressor",
      x: 610,
      y: 105,
      width: 118,
      height: 82,
    },
  },
  valves: {
    "XMV(1)": {
      id: "XMV(1)",
      label: "D feed",
      x: 96,
      y: 306,
      orientation: "horizontal",
      location: "Reactor feed",
    },
    "XMV(2)": {
      id: "XMV(2)",
      label: "E feed",
      x: 96,
      y: 354,
      orientation: "horizontal",
      location: "Reactor feed",
    },
    "XMV(3)": {
      id: "XMV(3)",
      label: "A feed",
      x: 96,
      y: 258,
      orientation: "horizontal",
      location: "Reactor feed",
    },
    "XMV(4)": {
      id: "XMV(4)",
      label: "A+C feed",
      x: 96,
      y: 402,
      orientation: "horizontal",
      location: "Reactor feed",
    },
    "XMV(5)": {
      id: "XMV(5)",
      label: "Recycle",
      x: 472,
      y: 135,
      orientation: "horizontal",
      location: "Compressor recycle",
    },
    "XMV(6)": {
      id: "XMV(6)",
      label: "Purge",
      x: 815,
      y: 213,
      orientation: "vertical",
      location: "Separator purge",
    },
    "XMV(7)": {
      id: "XMV(7)",
      label: "Separator liquid",
      x: 812,
      y: 430,
      orientation: "horizontal",
      location: "Separator outlet",
    },
    "XMV(8)": {
      id: "XMV(8)",
      label: "Product",
      x: 1084,
      y: 502,
      orientation: "horizontal",
      location: "Stripper outlet",
    },
    "XMV(9)": {
      id: "XMV(9)",
      label: "Steam",
      x: 892,
      y: 535,
      orientation: "vertical",
      location: "Stripper reboiler",
    },
    "XMV(10)": {
      id: "XMV(10)",
      label: "Reactor CW",
      x: 198,
      y: 498,
      orientation: "vertical",
      location: "Reactor cooling",
    },
    "XMV(11)": {
      id: "XMV(11)",
      label: "Condenser CW",
      x: 452,
      y: 344,
      orientation: "horizontal",
      location: "Separator cooling",
    },
    "XMV(12)": {
      id: "XMV(12)",
      label: "Agitator",
      x: 256,
      y: 278,
      orientation: "horizontal",
      location: "Reactor",
    },
  },
  measurements: {
    "XMEAS(1)": {
      id: "XMEAS(1)",
      label: "A feed",
      x: 162,
      y: 247,
      location: "Reactor feed",
    },
    "XMEAS(2)": {
      id: "XMEAS(2)",
      label: "D feed",
      x: 162,
      y: 295,
      location: "Reactor feed",
    },
    "XMEAS(3)": {
      id: "XMEAS(3)",
      label: "E feed",
      x: 162,
      y: 343,
      location: "Reactor feed",
    },
    "XMEAS(4)": {
      id: "XMEAS(4)",
      label: "A+C feed",
      x: 162,
      y: 391,
      location: "Reactor feed",
    },
    "XMEAS(5)": {
      id: "XMEAS(5)",
      label: "Recycle flow",
      x: 532,
      y: 119,
      location: "Compressor recycle",
    },
    "XMEAS(6)": {
      id: "XMEAS(6)",
      label: "Reactor feed rate",
      x: 196,
      y: 372,
      location: "Reactor inlet",
    },
    "XMEAS(7)": {
      id: "XMEAS(7)",
      label: "Reactor pressure",
      x: 275,
      y: 278,
      location: "Reactor",
    },
    "XMEAS(8)": {
      id: "XMEAS(8)",
      label: "Reactor level",
      x: 348,
      y: 384,
      location: "Reactor",
    },
    "XMEAS(9)": {
      id: "XMEAS(9)",
      label: "Reactor temperature",
      x: 348,
      y: 438,
      location: "Reactor",
    },
    "XMEAS(10)": {
      id: "XMEAS(10)",
      label: "Purge rate",
      x: 858,
      y: 194,
      location: "Separator purge",
    },
    "XMEAS(11)": {
      id: "XMEAS(11)",
      label: "Separator temperature",
      x: 672,
      y: 404,
      location: "Separator",
    },
    "XMEAS(12)": {
      id: "XMEAS(12)",
      label: "Separator level",
      x: 744,
      y: 404,
      location: "Separator",
    },
    "XMEAS(13)": {
      id: "XMEAS(13)",
      label: "Separator pressure",
      x: 690,
      y: 278,
      location: "Separator",
    },
    "XMEAS(14)": {
      id: "XMEAS(14)",
      label: "Separator underflow",
      x: 808,
      y: 468,
      location: "Separator outlet",
    },
    "XMEAS(15)": {
      id: "XMEAS(15)",
      label: "Stripper level",
      x: 1058,
      y: 388,
      location: "Stripper",
    },
    "XMEAS(16)": {
      id: "XMEAS(16)",
      label: "Stripper pressure",
      x: 998,
      y: 260,
      location: "Stripper",
    },
    "XMEAS(17)": {
      id: "XMEAS(17)",
      label: "Stripper underflow",
      x: 1066,
      y: 556,
      location: "Stripper outlet",
    },
    "XMEAS(18)": {
      id: "XMEAS(18)",
      label: "Stripper temperature",
      x: 1058,
      y: 438,
      location: "Stripper",
    },
    "XMEAS(19)": {
      id: "XMEAS(19)",
      label: "Steam flow",
      x: 858,
      y: 568,
      location: "Stripper reboiler",
    },
    "XMEAS(20)": {
      id: "XMEAS(20)",
      label: "Compressor work",
      x: 666,
      y: 83,
      location: "Compressor",
    },
    "XMEAS(21)": {
      id: "XMEAS(21)",
      label: "Reactor CW outlet",
      x: 196,
      y: 548,
      location: "Reactor cooling",
    },
    "XMEAS(22)": {
      id: "XMEAS(22)",
      label: "Separator CW outlet",
      x: 520,
      y: 360,
      location: "Separator cooling",
    },
    "XMEAS(23)": {
      id: "XMEAS(23)",
      label: "Feed A %",
      x: 190,
      y: 504,
      location: "Reactor feed composition",
    },
    "XMEAS(24)": {
      id: "XMEAS(24)",
      label: "Feed B %",
      x: 232,
      y: 504,
      location: "Reactor feed composition",
    },
    "XMEAS(25)": {
      id: "XMEAS(25)",
      label: "Feed C %",
      x: 274,
      y: 504,
      location: "Reactor feed composition",
    },
    "XMEAS(26)": {
      id: "XMEAS(26)",
      label: "Feed D %",
      x: 316,
      y: 504,
      location: "Reactor feed composition",
    },
    "XMEAS(27)": {
      id: "XMEAS(27)",
      label: "Feed E %",
      x: 358,
      y: 504,
      location: "Reactor feed composition",
    },
    "XMEAS(28)": {
      id: "XMEAS(28)",
      label: "Feed F %",
      x: 400,
      y: 504,
      location: "Reactor feed composition",
    },
    "XMEAS(29)": {
      id: "XMEAS(29)",
      label: "Purge A %",
      x: 890,
      y: 116,
      location: "Purge composition",
    },
    "XMEAS(30)": {
      id: "XMEAS(30)",
      label: "Purge B %",
      x: 932,
      y: 116,
      location: "Purge composition",
    },
    "XMEAS(31)": {
      id: "XMEAS(31)",
      label: "Purge C %",
      x: 974,
      y: 116,
      location: "Purge composition",
    },
    "XMEAS(32)": {
      id: "XMEAS(32)",
      label: "Purge D %",
      x: 1016,
      y: 116,
      location: "Purge composition",
    },
    "XMEAS(33)": {
      id: "XMEAS(33)",
      label: "Purge E %",
      x: 890,
      y: 154,
      location: "Purge composition",
    },
    "XMEAS(34)": {
      id: "XMEAS(34)",
      label: "Purge F %",
      x: 932,
      y: 154,
      location: "Purge composition",
    },
    "XMEAS(35)": {
      id: "XMEAS(35)",
      label: "Purge G %",
      x: 974,
      y: 154,
      location: "Purge composition",
    },
    "XMEAS(36)": {
      id: "XMEAS(36)",
      label: "Purge H %",
      x: 1016,
      y: 154,
      location: "Purge composition",
    },
    "XMEAS(37)": {
      id: "XMEAS(37)",
      label: "Product D %",
      x: 976,
      y: 628,
      location: "Product composition",
    },
    "XMEAS(38)": {
      id: "XMEAS(38)",
      label: "Product E %",
      x: 1018,
      y: 628,
      location: "Product composition",
    },
    "XMEAS(39)": {
      id: "XMEAS(39)",
      label: "Product F %",
      x: 1060,
      y: 628,
      location: "Product composition",
    },
    "XMEAS(40)": {
      id: "XMEAS(40)",
      label: "Product G %",
      x: 1102,
      y: 628,
      location: "Product composition",
    },
    "XMEAS(41)": {
      id: "XMEAS(41)",
      label: "Product H %",
      x: 1144,
      y: 628,
      location: "Product composition",
    },
  },
};
